import COLORS from "../../themes/Colors";

export const test = [
  {
    seat: [
      { id: 1, ocupado: false, cat: "VP", costo: 4000 },
      { id: 2, ocupado: false, cat: "general", costo: 2000 },
      { id: 3, ocupado: false, cat: "SG", costo: 4500 },
      { id: 4, ocupado: false, cat: "general", costo: 2000 },
      { id: 5, ocupado: false, cat: "general", costo: 2000 },
      { id: 6, ocupado: true, cat: "general", costo: 2000 },
      { id: 7, ocupado: false, cat: "general", costo: 2000 },
      { id: 8, ocupado: false, cat: "general", costo: 2000 },
      { id: 9, ocupado: false, cat: "general", costo: 2000 },
      { id: 10, ocupado: false, cat: "general", costo: 2000 },
      { id: 11, ocupado: true, cat: "general", costo: 2000 },
    ],
    avaliable: 1,
    category: "A",
    pattern: "2,5,2",
  },

  {
    seat: [
      { id: 23, ocupado: false, cat: "SG", costo: 4500 },
      { id: 24, ocupado: false, cat: "VP", costo: 4000 },
      { id: 25, ocupado: false, cat: "SG", costo: 4500 },
      { id: 26, ocupado: false, cat: "general", costo: 2000 },
      { id: 27, ocupado: false, cat: "SG", costo: 4500 },
      { id: 28, ocupado: false, cat: "general", costo: 2000 },
      { id: 29, ocupado: false, cat: "SG", costo: 4500 },
      { id: 30, ocupado: false, cat: "VP", costo: 4000 },
      { id: 31, ocupado: false, cat: "general", costo: 2000 },
      { id: 32, ocupado: false, cat: "SG", costo: 4500 },
      { id: 33, ocupado: false, cat: "general", costo: 2000 },
    ],
    avaliable: 1,
    category: "B",
    pattern: "2,5,2",
  },
  {
    seat: [
      { id: 34, ocupado: true, cat: "general", costo: 2000 },
      { id: 35, ocupado: false, cat: "VP", costo: 4000 },
      { id: 36, ocupado: false, cat: "general", costo: 2000 },
      { id: 37, ocupado: false, cat: "general", costo: 2000 },
      { id: 38, ocupado: false, cat: "general", costo: 2000 },
      { id: 39, ocupado: false, cat: "SG", costo: 4500 },
      { id: 40, ocupado: false, cat: "general", costo: 2000 },
      { id: 41, ocupado: false, cat: "general", costo: 2000 },
      { id: 42, ocupado: false, cat: "general", costo: 2000 },
      { id: 43, ocupado: false, cat: "general", costo: 2000 },
      { id: 44, ocupado: true, cat: "general", costo: 2000 },
    ],
    avaliable: 1,
    category: "C",
    pattern: "2,5,2",
  },
  {
    seat: [
      { id: 46, ocupado: true, cat: "general", costo: 2000 },
      { id: 47, ocupado: false, cat: "general", costo: 2000 },
      { id: 48, ocupado: false, cat: "general", costo: 2000 },
      { id: 49, ocupado: false, cat: "VP", costo: 4000 },
      { id: 50, ocupado: false, cat: "general", costo: 2000 },
      { id: 51, ocupado: false, cat: "general", costo: 2000 },
      { id: 52, ocupado: false, cat: "general", costo: 2000 },
      { id: 53, ocupado: false, cat: "general", costo: 2000 },
      { id: 54, ocupado: false, cat: "general", costo: 2000 },
      { id: 55, ocupado: false, cat: "VP", costo: 4000 },
      { id: 56, ocupado: true, cat: "SG", costo: 4500 },
    ],
    avaliable: 1,
    category: "D",
    pattern: "2,5,2",
  },

  {
    seat: [
      { id: 57, ocupado: false, cat: "general", costo: 2000 },
      { id: 58, ocupado: false, cat: "general", costo: 2000 },
      { id: 59, ocupado: false, cat: "VP", costo: 4000 },
      { id: 60, ocupado: false, cat: "general", costo: 2000 },
      { id: 61, ocupado: false, cat: "general", costo: 2000 },
      { id: 62, ocupado: false, cat: "general", costo: 2000 },
      { id: 63, ocupado: true, cat: "general", costo: 2000 },
      { id: 64, ocupado: false, cat: "general", costo: 2000 },
      { id: 65, ocupado: false, cat: "SG", costo: 4500 },
      { id: 66, ocupado: false, cat: "general", costo: 2000 },
      { id: 67, ocupado: true, cat: "SG", costo: 4500 },
    ],
    avaliable: 1,
    category: "E",
    pattern: "2,5,2",
  },

  {
    seat: [
      { id: 68, ocupado: false, cat: "general", costo: 2000 },
      { id: 69, ocupado: false, cat: "general", costo: 2000 },
      { id: 70, ocupado: false, cat: "VP", costo: 4000 },
      { id: 71, ocupado: false, cat: "general", costo: 2000 },
      { id: 72, ocupado: false, cat: "general", costo: 2000 },
      { id: 73, ocupado: false, cat: "general", costo: 2000 },
      { id: 74, ocupado: true, cat: "general", costo: 2000 },
      { id: 75, ocupado: false, cat: "general", costo: 2000 },
      { id: 77, ocupado: false, cat: "SG", costo: 4500 },
      { id: 78, ocupado: false, cat: "general", costo: 2000 },
      { id: 79, ocupado: true, cat: "SG", costo: 4500 },
    ],
    avaliable: 1,
    category: "F",
    pattern: "2,5,2",
  },

  {
    seat: [
      { id: 80, ocupado: false, cat: "VP", costo: 4000 },
      { id: 81, ocupado: false, cat: "general", costo: 2000 },
      { id: 82, ocupado: false, cat: "general", costo: 2000 },
      { id: 83, ocupado: false, cat: "general", costo: 2000 },
      { id: 84, ocupado: false, cat: "general", costo: 2000 },
      { id: 85, ocupado: true, cat: "general", costo: 2000 },
      { id: 86, ocupado: false, cat: "general", costo: 2000 },
      { id: 87, ocupado: false, cat: "SG", costo: 4500 },
      { id: 88, ocupado: false, cat: "general", costo: 2000 },
      { id: 89, ocupado: true, cat: "SG", costo: 4500 },
      { id: 90, ocupado: false, cat: "general", costo: 2000 },
    ],
    avaliable: 1,
    category: "G",
    pattern: "2,5,2",
  },
];

export const arraySeat2 = [
  { id: 1, status: "Disponible", color: `green` },
  { id: 2, status: "Bloqueado", color: `${COLORS.primary}` },
  { id: 3, status: "Seleccionado", color: `${COLORS.red}` },
];

export const test2 = [
  [
    { name: "victor", id: 1, ocupado: false },
    { name: "Manuel", id: 2, ocupado: false },
    { name: "Starlyn", id: 3, ocupado: false },
    { name: "pedro", id: 4, ocupado: false },
    { name: "jose", id: 5, ocupado: false },
    { name: "marlon", id: 6, ocupado: true },
    { name: "tore", id: 7, ocupado: false },
    { name: "carlos", id: 8, ocupado: false },
  ],

  [
    { name: "victor", id: 1, ocupado: false },
    { name: "Manuel", id: 2, ocupado: false },
    { name: "Starlyn", id: 3, ocupado: false },
    { name: "pedro", id: 4, ocupado: false },
    { name: "jose", id: 5, ocupado: false },
    { name: "marlon", id: 6, ocupado: true },
    { name: "tore", id: 7, ocupado: false },
    { name: "carlos", id: 8, ocupado: false },
  ],
];
